repos:
  - repo: https://github.com/ambv/black
    rev: stable
    hooks:
      - id: black
        args: [--quiet]
        types:
          - python
        exclude: ^docs/conf.py$
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v1.4.0
    hooks:
      - id: check-yaml
        types:
          - yaml
      - id: debug-statements
        types:
          - python
      - id: flake8
        types:
          - python
        exclude: ^docs/conf.py$

  - repo: https://github.com/ambv/black
    rev: 20.8b1
    hooks:
      - id: black
        types:
         - python

  - repo: https://github.com/commitizen-tools/commitizen
    rev: master
    hooks:
      - id: commitizen
        stages: [commit-msg]

