version: 2

build:
  os: ubuntu-24.04
  tools:
    python: "3.11"

formats: all

sphinx:
  configuration: docs/conf.py

python:
  install:
    - path: .
      method: pip
    - requirements: docs/requirements.txt
